# Generated by Django 2.1.2 on 2018-11-04 13:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
